#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                on
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff40FF00
yabai -m config normal_window_border_color   0x00FFFFFF
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# mission-control desktop labels
yabai -m space 1 --label web
yabai -m space 2 --label development
yabai -m space 3 --label mail
yabai -m space 4 --label message
yabai -m space 5 --label conversation

#yabai -m config --space code  layout        stack

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^Firefox$" space=web
yabai -m rule --add app="^Google Chrome$" space=web
yabai -m rule --add app="^Safari$" space=web
yabai -m rule --add app="^idea$" space=development
yabai -m rule --add app="^Alacritty$" space=development
yabai -m rule --add app="^Postman$" space=development
yabai -m rule --add app="^Microsoft Outlook$" space=mail
yabai -m rule --add app="^Slack$" space=message
yabai -m rule --add app="^Discord$" space=message
yabai -m rule --add app="^Telegram$" space=message
yabai -m rule --add app="^WhatsApp$" space=message
yabai -m rule --add app="^Microsoft Teams$" space=conversation
yabai -m rule --add app="^zoom.us$" space=conversation
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Spotify$" layer=above manage=off
yabai -m rule --add app="^console$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 20
yabai -m config bottom_padding 20
yabai -m config left_padding 20
yabai -m config right_padding 20
yabai -m config window_gap 10

yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."

#END
