# Catppuccin Latte (light theme)
set -g status-justify "left"
set -g status "on"
set -g status-position "top"

set -g status-left-style "none"
set -g status-right-style "none"

set -g pane-border-style "fg=#DCE0E8"
set -g pane-active-border-style "fg=#4C4F69"

set -g message-style "fg=#4C4F69,bg=#E6E9EF"
set -g message-command-style "fg=#4C4F69,bg=#E6E9EF"

set -g status-style "bg=#EFF1F5,fg=#4C4F69"

setw -g window-status-style "none,fg=#4C4F69,bg=#EFF1F5"
setw -g window-status-activity-style "underscore,fg=#4C4F69,bg=#EFF1F5"
setw -g window-status-separator ""

setw -g window-status-format "#[fg=#4C4F69,bg=#EFF1F5] #I #W "
setw -g window-status-current-format "#[fg=#EFF1F5,bg=#1E66F5] #I #W "

set -g status-left "#[fg=#EFF1F5,bg=#4C4F69] #S #[fg=#4C4F69,bg=#EFF1F5]"
set -g status-right-length "100"
set -g status-left-length "100"
set -g status-right "#[fg=#4C4F69,bg=#EFF1F5] %a #[fg=#9CA0B0,bg=#EFF1F5] %Y-%m-%d %H:%M #[fg=#EFF1F5,bg=#4C4F69]  #h "

