# Catppuccin Mocha (dark theme)
set -g status-justify "left"
set -g status "on"
set -g status-position "top"

set -g status-left-style "none"
set -g status-right-style "none"

set -g pane-border-style "fg=#45475A"
set -g pane-active-border-style "fg=#CDD6F4"

set -g message-style "fg=#CDD6F4,bg=#313244"
set -g message-command-style "fg=#CDD6F4,bg=#313244"

set -g status-style "bg=#313244,fg=#CDD6F4"

setw -g window-status-style "none,fg=#CDD6F4,bg=#313244"
setw -g window-status-activity-style "underscore,fg=#CDD6F4,bg=#313244"
setw -g window-status-separator ""

setw -g window-status-format "#[fg=#CDD6F4,bg=#313244] #I #W "
setw -g window-status-current-format "#[fg=#313244,bg=#89B4FA] #I #W "

set -g status-left "#[fg=#313244,bg=#CDD6F4] #S #[fg=#CDD6F4,bg=#313244]"
set -g status-right-length "100"
set -g status-left-length "100"
set -g status-right "#[fg=#CDD6F4,bg=#313244] %a #[fg=#6C7086,bg=#313244] %Y-%m-%d %H:%M #[fg=#313244,bg=#CDD6F4]  #h"

